### ISSUE TITLE
Home screen should only be visible once user has completed oauth

### ISSUE THREAD

**Issue by suhanichawla** [MLH-Fellowship/Chamber-of-Secrets#22]
home screen served at /upload is accessible even if user isn't signed in
Add a higher order react component that allows user to access /upload screen only after they have completed oauth and are authenticated using signup or login. If the user is not authenticated, they should be redirected to authenticate screen. If the user has not completed oauth they should be redirected to oauth screen

**Comment by ksdkamesh99** [comment]
@suhanichawla  I want to work on this issue
